table DOL
	lineageTag: 52e3ae27-d155-4dda-81e5-678d0c90b7cb

	measure จำนวนรวม = COUNT(DOL[district_id])
		formatString: #,0
		lineageTag: da142550-87b0-4d92-83a6-94280d746e6e

	measure 'Cancel Rate อัตราการยกเลิก' =
			
			DIVIDE(
			    CALCULATE(COUNTROWS('DOL'), 'DOL'[service_status_display] = "ยกเลิก/ไม่สำเร็จ"),
			    COUNTROWS('DOL')
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 0faf5091-677f-492d-8c0f-8cfbc4509084

	measure 'Success Rate' =
			
			DIVIDE(
			    CALCULATE(COUNTROWS('DOL'), 'DOL'[service_status_display] = "สำเร็จ"),
			    COUNTROWS('DOL')
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f8b4736a-b747-4aa4-8c30-1efddac22a46

	measure 'Doing Rate' =
			
			DIVIDE(
			    CALCULATE(COUNTROWS('DOL'), 'DOL'[service_status_display] = "กำลังดำเนินการ"),
			    COUNTROWS('DOL')
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2ebeec6a-ae84-4e48-b178-b7ba1a47906d

	measure Filter_Date_Range = ```
			
			VAR MinDate = MIN('DOL'[service_date])
			VAR MaxDate = MAX('DOL'[service_date])
			
			VAR MinStr = 
			    IF(
			        NOT(ISBLANK(MinDate)),
			        YEAR(MinDate) & "-" & 
			        RIGHT("0" & MONTH(MinDate), 2) & "-" & 
			        RIGHT("0" & DAY(MinDate), 2),
			        ""
			    )
			
			VAR MaxStr = 
			    IF(
			        NOT(ISBLANK(MaxDate)),
			        YEAR(MaxDate) & "-" & 
			        RIGHT("0" & MONTH(MaxDate), 2) & "-" & 
			        RIGHT("0" & DAY(MaxDate), 2),
			        ""
			    )
			
			RETURN
			IF(
			    ISBLANK(MinDate) || ISBLANK(MaxDate),
			    "-",
			    MinStr & " → " & MaxStr
			)
			```
		lineageTag: 7e730829-e6d1-4a38-90de-06b31a0d30f3

	column task_id
		dataType: string
		lineageTag: f1939569-8279-4610-91e9-6a7e4dade252
		summarizeBy: none
		sourceColumn: task_id

		annotation SummarizationSetBy = Automatic

	column task_code
		dataType: int64
		formatString: #,0
		lineageTag: 1397ae8c-6ee4-43b2-b647-bef82487423a
		summarizeBy: sum
		sourceColumn: task_code

		annotation SummarizationSetBy = Automatic

	column title_deed
		dataType: string
		lineageTag: 224ece33-6db2-48b3-adb0-d8b5b83f3472
		summarizeBy: none
		sourceColumn: title_deed

		annotation SummarizationSetBy = Automatic

	column task_remark
		dataType: string
		lineageTag: ec25d306-4b07-4c68-b67b-fd393aaaa89e
		summarizeBy: none
		sourceColumn: task_remark

		annotation SummarizationSetBy = Automatic

	column document_type_id
		dataType: string
		lineageTag: f0957ae4-480c-49e4-b517-5c14164426bf
		summarizeBy: none
		sourceColumn: document_type_id

		annotation SummarizationSetBy = Automatic

	column document_type_name
		dataType: string
		lineageTag: f44230cd-05e5-4804-9dd3-92685c59a5da
		summarizeBy: none
		sourceColumn: document_type_name

		annotation SummarizationSetBy = Automatic

	column service_group_id
		dataType: string
		lineageTag: edd83961-440e-40ea-b23f-728c94faf620
		summarizeBy: none
		sourceColumn: service_group_id

		annotation SummarizationSetBy = Automatic

	column service_group_name
		dataType: string
		lineageTag: ab180c22-afcd-4b14-9879-62103336f0e5
		summarizeBy: none
		sourceColumn: service_group_name

		annotation SummarizationSetBy = Automatic

	column service_type_id
		dataType: string
		lineageTag: 6bc9c58a-06fe-4487-bf1b-c1c822e7ab00
		summarizeBy: none
		sourceColumn: service_type_id

		annotation SummarizationSetBy = Automatic

	column service_type_name
		dataType: string
		lineageTag: 3b928cc6-1081-465e-ba5b-177db5452be6
		summarizeBy: none
		sourceColumn: service_type_name

		annotation SummarizationSetBy = Automatic

	column last_dep_id
		dataType: string
		lineageTag: 886dad56-48aa-4910-9cc6-5babe34d834f
		summarizeBy: none
		sourceColumn: last_dep_id

		annotation SummarizationSetBy = Automatic

	column last_department_name
		dataType: string
		lineageTag: ccc1d660-5aca-4baa-8404-8daad93b8e56
		summarizeBy: none
		sourceColumn: last_department_name

		annotation SummarizationSetBy = Automatic

	column last_process_no
		dataType: string
		lineageTag: c93d9a60-5c30-408a-9e65-2865be2a6986
		summarizeBy: none
		sourceColumn: last_process_no

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column district_id
		dataType: string
		lineageTag: ffbec39a-b2da-454a-a908-4c1ccf384e59
		summarizeBy: none
		sourceColumn: district_id

		annotation SummarizationSetBy = Automatic

	column district_name
		dataType: string
		lineageTag: 2c81b10d-ee23-42ee-8f53-39fc95868824
		summarizeBy: none
		sourceColumn: district_name

		annotation SummarizationSetBy = Automatic

	column service_time_id
		dataType: string
		lineageTag: 196f801a-ea3f-4b32-878b-282d581f8777
		summarizeBy: none
		sourceColumn: service_time_id

		annotation SummarizationSetBy = Automatic

	column standard_service_time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5748aea2-8147-404d-8c4c-4be22ed29987
		summarizeBy: none
		sourceColumn: standard_service_time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column standard_days
		dataType: int64
		formatString: 0
		lineageTag: a750e584-1a1f-4456-a5be-3a1044651d55
		summarizeBy: sum
		sourceColumn: standard_days

		annotation SummarizationSetBy = Automatic

	column service_key_data
		dataType: string
		lineageTag: 06354c79-2bc3-491b-bf18-b86864064700
		summarizeBy: none
		sourceColumn: service_key_data

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: string
		lineageTag: c52a7dad-41a6-43c2-bdb8-4c8f6ff46a1e
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column employee_department_name
		dataType: string
		lineageTag: 453d7e8f-e94f-4911-b337-d2a177b6bcea
		summarizeBy: none
		sourceColumn: employee_department_name

		annotation SummarizationSetBy = Automatic

	column service_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: c42f5fcb-b2c2-46b5-bd08-be0cb241f659
		summarizeBy: none
		sourceColumn: service_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column task_date,start_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 1d32c7d2-8466-44bc-b2a6-3d92fbc976e3
		summarizeBy: none
		sourceColumn: task_date,start_datetime

		variation Variation
			isDefault
			relationship: 229c5f69-18e3-425a-97b8-2cb8803d8a29
			defaultHierarchy: LocalDateTable_c619e9a8-d1d1-4849-85c0-6d1566e69d06.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column start_datetime
		dataType: dateTime
		formatString: General Date
		lineageTag: d29a6f56-9712-489b-a866-7bdffa550b3b
		summarizeBy: none
		sourceColumn: start_datetime

		variation Variation
			isDefault
			relationship: dbe717f3-3d97-48ec-8f24-71d723dfac79
			defaultHierarchy: LocalDateTable_3d1cc5d1-a5a4-4a46-bf3d-c66de80cdab3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column last_update_datetime
		dataType: string
		lineageTag: 60c598fb-dddc-446c-8897-35db59deb2ba
		summarizeBy: none
		sourceColumn: last_update_datetime

		annotation SummarizationSetBy = Automatic

	column actual_duration_minutes
		dataType: string
		lineageTag: 58e69ac8-bb86-4723-b73d-bf1fed7d375c
		summarizeBy: none
		sourceColumn: actual_duration_minutes

		annotation SummarizationSetBy = Automatic

	column raw_result
		dataType: string
		lineageTag: bc9b7ddf-2778-458c-bf05-474b64783040
		summarizeBy: none
		sourceColumn: raw_result

		annotation SummarizationSetBy = Automatic

	column service_status_display
		dataType: string
		lineageTag: cd235dab-884f-49b4-aea8-7cfff6235fc5
		summarizeBy: none
		sourceColumn: service_status_display

		annotation SummarizationSetBy = Automatic

	column service_status_display(ENG)
		dataType: string
		lineageTag: 733c47e9-6112-482c-b5d5-cdc7278deb16
		summarizeBy: none
		sourceColumn: service_status_display(ENG)

		annotation SummarizationSetBy = Automatic

	column วันในสัปดาห์ = FORMAT('DOL'[service_date], "dddd", "th-TH")
		lineageTag: b4bc05e7-0b48-4abf-87ba-9a8362da855f
		summarizeBy: none
		sortByColumn: ลำดับวัน

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column ลำดับวัน = WEEKDAY('DOL'[service_date], 2)
		formatString: 0
		lineageTag: 6508c6c4-3b44-4095-b115-b87618dafb18
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column เลขลำดับสัปดาห์ =
			
			VAR CurrentDate = 'DOL'[service_date]
			VAR FirstDayOfMonth = STARTOFMONTH('DOL'[service_date])
			VAR FirstWeekday = WEEKDAY(FirstDayOfMonth, 2) -- ต้องใส่เลข 2 เพื่อตัดสัปดาห์ตามวันจันทร์
			RETURN
			    INT((DAY(CurrentDate) + FirstWeekday - 2) / 7) + 1
		formatString: 0
		lineageTag: bd314d6c-50df-4d9b-aee3-d4500d769ca8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ช่วงเวลา = ```
			
			SWITCH (
			    TRUE(),
			    HOUR ( 'DOL'[task_date,start_datetime] ) < 12, "เช้า", HOUR ( 'DOL'[task_date,start_datetime] ) < 13, "เที่ยง", 
			    HOUR ( 'DOL'[task_date,start_datetime] ) < 18, "บ่าย",                                                                                                                          "กลางคืน"
			)
			```
		lineageTag: 766ff87a-8c26-4643-85a9-6263706393d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Process_Name =
			
			SWITCH(
			    'DOL'[last_process_no],
			    "3", "ขั้นตอน 3: งานเบ็ดเตล็ด",
			    "4", "ขั้นตอน 4: งานนิติกรรมและงานด่วน",
			    "5", "ขั้นตอน 5: งานหนังสือสำคัญ/ประกาศ",
			    "7", "ขั้นตอน 7: ตรวจสอบรังวัด",
			    "8", "ขั้นตอน 8: งานรังวัดที่ดิน",
			    "อื่นๆ"
			)
		lineageTag: 4c6e00cd-a024-4d70-8c72-31ef4bdd46fb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition DOL = m
		mode: import
		source =
				let
				  Source = GoogleSheets.Contents("https://docs.google.com/spreadsheets/d/19AW5VGigzA-erwJo9dq20_FyT9L5GVDmy1zXszxIrVM/edit?usp=sharing"),
				  #"Navigation 1" = Source{[name = "DOL", ItemKind = "Table"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"task_id", type text}, {"task_code", Int64.Type}, {"title_deed", type any}, {"task_remark", type any}, {"document_type_id", type text}, {"document_type_name", type text}, {"service_group_id", type text}, {"service_group_name", type text}, {"service_type_id", type text}, {"service_type_name", type text}, {"last_dep_id", type text}, {"last_department_name", type text}, {"last_process_no", Int64.Type}, {"district_id", type text}, {"district_name", type text}, {"service_time_id", type text}, {"standard_service_time", type time}, {"standard_days", Int64.Type}, {"service_key_data", type text}, {"employee_id", type text}, {"employee_department_name", type text}, {"service_date", type date}, {"task_date,start_datetime", type datetime}, {"start_datetime", type datetime}, {"last_update_datetime", type text}, {"actual_duration_minutes", type text}, {"raw_result", type text}, {"service_status_display", type text}, {"service_status_display(ENG)", type text}}),
				    #"Replaced Errors" = Table.ReplaceErrorValues(#"Changed Type", {{"start_datetime", null}}),
				    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Replaced Errors", {{"task_code", 1}}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Errors1", each true),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","undefined","อื่นๆ",Replacer.ReplaceText,{"document_type_name"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

